#!/bin/bash

set -e

should_update=false

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    --update)
    should_update=true

    shift
    ;;
    *)
    POSITIONAL+=("$1")
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}"

should_log_wait_event=true
while (! docker stats --no-stream > /dev/null 2>&1 ); do
    if [ "$should_log_wait_event" = true ] ; then
        >&2 echo "Waiting for Docker..."
        should_log_wait_event=false
    fi
    sleep 2
done

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export WORKING_DIR="$( dirname "$DIR" )"
if  [ "$should_update" = true ] ; then
    docker image prune -f
    docker container prune -f
    docker-compose -f "$DIR/docker/docker-compose.yaml" build --no-cache
fi

docker-compose -f "$DIR/docker/docker-compose.yaml" run --user $(id -u):$(id -g) build "$@"
