name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-monterey-arm, macos-monterey-intel]

    steps:

    - name: Ensure Homebrew is on the path (must be installed for Git-LFS support)
      if: matrix.os == 'macos-monterey-arm' || matrix.os == 'macos-monterey-intel'
      run:
        echo "/opt/homebrew/bin" >> $GITHUB_PATH

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true

    - name: Run tests
      run: |
        python3 -u incontext --verbose tests
