name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-monterey-m1]

    steps:

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run tests
      run: |
        python3 -u incontext tests
