name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: Ubuntu-20.04

    steps:
      
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Run tests
      run: |
        python3 -u incontext tests

  documentation:
      
    runs-on: Ubuntu-20.04
    
    steps:
      
    - name: Wait for other builds to finish
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        path: incontext
        
    - name: Checkout site repository
      uses: actions/checkout@v2
      with:
        repository: jbmorley/incontext-site
        ref: main
        path: site
        token: ${{ secrets.TOKEN }}
        
    - name: Build documentation
      run: |
        python3 -u incontext/incontext build-documentation site

    - name: Commit documentation
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update auto-generated documentation
        repository: site
        branch: main
