name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        experimental: [false]
        include:
        - os: macos-monterey-m1
          experimental: true

    steps:

    - name: Ensure Homebrew is on the path (must be installed)
      if: matrix.os == 'macos-monterey-m1'
      run:
        echo "/opt/homebrew/bin" >> $GITHUB_PATH

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true

    - name: Run tests
      run: |
        python3 -u incontext --verbose tests
